[FEATURE] Adding tandem pcie programmation to our flow (#14)
* [FEAT] initial commit for tandem

* [CLEANUP] typos

* [CLEANUP] cleaning up comments and file that was added by mistake

* [DOC] adding tandem in documentation

* [FIX] switching modprobe -r to rmmod for un-installed modules

* [DOC] clarifying documentation for tandem programming + slight formatting

* [CLEANUP] typos

* [DOC] clarifying two step programming with JTAG/PCIE

* [BUGFIX] create_shell.tcl needs ntt_psi as argument. Need to specify this argument when calling by its own (like in just generate_shell) or with source. Use argc and argv for that. If not given use ntt_psi=128.

* [BUGFIX] removing the circumvention of ntt_psi of hpu_plug

* [DOC] Apply suggestions from code review

Co-authored-by: JJ-hw <110426712+JJ-hw@users.noreply.github.com>

* [CLEANUP] removing not needed sudo for dma-ctl

* [FIX] adding a sleep to be safe, on certain devices this is needed to wait properly the full pcie rescan

* [DOC] updating note on linux distributions

* [CLEANUP] Apply suggestions from code review

Co-authored-by: JJ-hw <110426712+JJ-hw@users.noreply.github.com>

* [DOC] updating docs for Almalinux and usage of xbtest without hw-disc

* [DOC] cleanup

* [DOC] cleanup

---------

Co-authored-by: JJ-hw <110426712+JJ-hw@users.noreply.github.com>

diff --git a/versal/justfile b/versal/justfile
--- a/versal/justfile
+++ b/versal/justfile
@@ -28,6 +28,7 @@ DEFAULT_RTL_FLAGS := "-F TOP_BATCH TOP_BATCH_TOPhpu_BPBS16_TPBS32 -F TOP_PCMAX  
 
 # By default we want to build vivado projects from scratch : from project generation
 DEFAULT_STEP := "new"
+DEFAULT_STAGE := "all"
 
 DEFAULT_VIVADO_OPT := 'D:MEMORY_FILE_PATH=\"${PROJECT_DIR}/hw/\"'
 
@@ -93,6 +94,74 @@ build TOP_IP STEP=DEFAULT_STEP RTL_FLAGS=DEFAULT_RTL_FLAGS VIVADO_OPT=DEFAULT_VI
   export DESIGN_NAME={{TOP_IP}}
   vivado -log {{OUTDIR}}/vivado_integration_{{STEP}}.log -nojournal -mode batch -source {{SCRIPT_DIR}}/build_all.tcl -tclargs {{OUTDIR}} {{STEP}} "{{VIVADO_OPT}}" | tee {{OUTDIR}}/just_build_{{TOP_IP}}.log
 
+program TOP_IP STAGE=DEFAULT_STAGE:
+  #!/usr/bin/env bash
+  TOP_IP={{TOP_IP}}
+  STAGE={{STAGE}}
+  DRIVERS=("qdma_pf" "ami")
+
+  [[ "$STAGE" != "stage1" && "$STAGE" != "stage2" && "$STAGE" != "all" ]] && echo "[ERROR] please choose a correct stage \"all\", \"stage1\" or \"stage2\"" && exit 1
+
+  # Function to check if a driver is loaded
+  check_driver() {
+      for driver in "${DRIVERS[@]}"; do
+        if lsmod | grep -q "^$driver "; then
+            echo "[WARNING] Driver $driver is present, will unload"
+            sudo rmmod $driver
+        else
+            echo "[INFO] Driver $driver already unloaded"
+        fi
+      done
+  }
+
+  if [[ "$STAGE" = "all" || "$STAGE" = "stage1" ]]; then
+    echo "[INFO] Stage 1 programming"
+    STAGE1_PATH=$(realpath "output/${TOP_IP}_tandem1.pdi")
+
+    # checks
+    check_driver
+    [ ! -f "$STAGE1_PATH" ] && { echo "[ERROR] $STAGE1_PATH not found" && exit 1; } || { echo "[INFO] Found $STAGE1_PATH"; }
+
+    vivado -mode batch -source scripts/jtag/program_stage1.tcl -tclargs $STAGE1_PATH
+  fi
+
+  if [[ "$STAGE" = "all" || "$STAGE" = "stage2" ]]; then
+    echo "[INFO] Stage 2 programming"
+
+    PCIE_CARD=$(lspci -d 10ee:50b4)
+    DEVICE="${PCIE_CARD%%:*}"
+    QMAX="/sys/bus/pci/devices/0000:$DEVICE:00.1/qdma/qmax"
+    STAGE2_PATH=$(realpath "output/${TOP_IP}_tandem2.pdi")
+    STAGE2_SIZE=$(stat -c%s $STAGE2_PATH)
+
+    # checks
+    [ -z "$PCIE_CARD" ] && { echo "[ERROR] V80 PCI device not found" && exit 1; } || { echo "[INFO] Found PCI device"; }
+    check_driver
+    [ ! -f "$STAGE2_PATH" ] && { echo "[ERROR] $STAGE2_PATH not found" && exit 1; } || { echo "[INFO] Found $STAGE2_PATH"; }
+    bootgen -arch versal -read $STAGE2_PATH | grep "rpu_subsystem" && { echo "[INFO] Found elf in stage 2 $STAGE2_PATH"; } || \
+    { echo "[ERROR] No elf found in $STAGE2_PATH ... abort" ; exit 1; }
+
+    echo "[INFO] Updating physical functions status"
+    sudo bash -c "echo 1 > /sys/bus/pci/devices/0000:$DEVICE:00.0/remove"
+    sudo bash -c "echo 1 > /sys/bus/pci/devices/0000:$DEVICE:00.1/remove"
+    sudo bash -c "echo 1 > /sys/bus/pci/rescan"
+    sleep 2
+
+    echo "[INFO] Initializing queues"
+    sudo bash -c "echo 100 > $QMAX"
+    dma-ctl qdma${DEVICE}001 q add idx 0 dir h2c
+    dma-ctl qdma${DEVICE}001 q start idx 0 dir h2c aperture_sz 4096
+
+    echo "[INFO] Programming stage 2 bitstream"
+    dma-to-device -d /dev/qdma${DEVICE}001-MM-0 -f ${STAGE2_PATH} -s ${STAGE2_SIZE} -a 0x000102100000
+
+    echo "[INFO] Reloading drivers and updating pci registers"
+    # we must wait a bit for everything to settle down
+    sleep 1
+    sudo bash -c "echo 1 > /sys/bus/pci/devices/0000:$DEVICE:00.0/remove"
+    sudo bash -c "echo 1 > /sys/bus/pci/rescan"
+  fi
+
 #------------------------------------------------
 ### Compile FW
 #------------------------------------------------
@@ -150,6 +219,35 @@ merge_elf TOP_IP:
   bootgen -arch versal -image $OUTPUT_FILE -w -o $PDI_PATH
 
 #------------------------------------------------
+### Merge tandem pdi together
+#------------------------------------------------
+# this task is meant to be used for two tandem stages
+merge_pdi TOP_IP:
+  #!/usr/bin/env bash
+  set -euxo pipefail
+  # var -----------------------------------------------------------------------
+  PDI_PATH={{OUTDIR}}/{{TOP_IP}}.pdi
+  STAGE_1_PATH={{OUTDIR}}/{{TOP_IP}}_tandem1.pdi
+  STAGE_2_PATH={{OUTDIR}}/{{TOP_IP}}_tandem2.pdi
+
+  # file handling -------------------------------------------------------------
+  if [[ -f "$STAGE_1_PATH"  && -f "$STAGE_2_PATH" ]]; then
+    echo "[INFO] Found stage 1 and 2 files"
+  else
+    echo "[ERROR] pdi not found"
+    exit 1
+  fi
+
+  TEMPLATE_FILE=$PROJECT_DIR/versal/scripts/fpt/template/flash_template.json.j2
+  OUTPUT_FILE={{OUTDIR}}/pdi_combine.bif
+
+  # merge elf and top pdi -----------------------------------------------------
+  sed -e "s#\^\^stage_1_path\^\^#$STAGE_1_PATH#g" \
+          -e "s#\^\^stage_2_path\^\^#$STAGE_2_PATH#g" "$TEMPLATE_FILE" > "$OUTPUT_FILE"
+
+  bootgen -arch versal -image $OUTPUT_FILE -w -o $PDI_PATH
+
+#------------------------------------------------
 ### Rewrite flash
 #------------------------------------------------
 # Rewrite flash
@@ -164,7 +262,7 @@ rewrite_flash:
     exit 1
   fi
 
-  vivado -log {{OUTDIR}}/rewrite_flash.log -nojournal -mode batch -source {{SCRIPT_DIR}}/fully_rewrite_flash.tcl
+  vivado -log {{OUTDIR}}/rewrite_flash.log -nojournal -mode batch -source {{SCRIPT_DIR}}/jtag/fully_rewrite_flash.tcl
 
 #------------------------------------------------
 ### Utility commands
